= Readme: PTREQ - Pure Text Requirements
felix.haeberle@icloud.com
2024-06-23
////
file-id: e192348f-f190-49d0-9cf5-95f86adac301
file-type: project-readme
project-name: ptreq
project-id: 11320d17-f243-4e2f-a841-e52098b2b439
////
== Experimental Project to create text-based requirements for software projects

This project is an experiment to create a text-based requirements system for software projects. The idea is to create a simple, easy to use, and easy to understand system that can be used to create and manage requirements for software projects.

It uses:

. git for version control
. python to automate the process
. poetry for the package management (for best results install `poetry` with `pipx`)
. asciidoctor for the documentation markup (using ruby)
. https://github.com/domgold/asciidoctor-gherkin-extension

== A Requirement 

=== Structure

[ditaa]
----

----

=== Definition With Gherkin

Is a statement of what a system should do or how it should behave. It is a description of the system's functionality, performance, and other attributes.

A requirement should be defined with a clear and concise statement that can be easily understood by all stakeholders. For this project we suggest to use the syntax behaviour driven development (BDD):

. `GIVEN`: the context or preconditions
. `WHEN`: the action
. `THEN`: the expected outcome

All sections can be combined with `AND` so that a 

[source,gerkin]
----
GIVEN a user is logged in 
GIVEN the profile page is active
----

equals the 
[source,gerkin]
----
GIVEN a user is logged in 
AND the profile page is active
----

